sudo: required
language: generic

services:
  - docker


before_install:
  - docker build -t geliarda/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true geliarda/docker-react npm run test -- --coverage
